
(()=>{
'use strict';
const DATA=window.C2A_DATA; const CORE=DATA.course.lessons.filter(x=>x.requirement.startsWith('CORE')); const PL=DATA.course.lessons.filter(x=>!x.requirement.startsWith('CORE'));
const TABS=['Today','Learn','Course','Repair','Evidence','Jobs','Reports','Settings'];
const K='c2a_mentor_2026_rc1'; // storage key intentionally preserved for progress continuity
const fresh=()=>({v:2,theme:'dark',fontScale:1,activeTab:'Today',moduleFilter:'ALL',plEnabled:false,lessons:{},gates:{},moduleIntro:{},sessions:[],activeSession:null,evidence:{},repairNotes:{},careerNotes:'',updatedAt:new Date().toISOString()});
let S; try{S=Object.assign(fresh(),JSON.parse(localStorage.getItem(K)||'{}'))}catch(e){S=fresh()}
S.lessons=S.lessons||{};S.gates=S.gates||{};S.evidence=S.evidence||{};S.repairNotes=S.repairNotes||{};S.moduleIntro=S.moduleIntro||{};S.sessions=S.sessions||[];
const qs=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){S.updatedAt=new Date().toISOString();localStorage.setItem(K,JSON.stringify(S));applyTheme()}
function applyTheme(){document.documentElement.dataset.theme=S.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):S.theme;document.documentElement.style.setProperty('--scale',String(S.fontScale||1))}
function ls(id){return S.lessons[id]||(S.lessons[id]={attempt:false,review:false,retry:false,explain:false,mastered:false,developing:false})}
function gateDefaults(g){return {assigned:g==='A',attempt:false,review:false,reviewViewed:false,passed:false,developing:false,repair:false,repairDone:false,repairEvidence:''}}
function normalizeGate(x,g){x.assigned=g==='A'?true:(typeof x.assigned==='boolean'?x.assigned:!!(x.attempt||x.review||x.passed||x.developing||x.repair));x.attempt=!!x.attempt;x.review=!!x.review;x.reviewViewed=!!(x.reviewViewed||x.review);x.passed=!!x.passed;x.developing=!!x.developing;x.repairDone=!!(x.repairDone||x.repair);x.repair=!!x.repairDone;x.repairEvidence=String(x.repairEvidence||'');return x}
function gs(mid,g='A'){S.gates[mid]=S.gates[mid]||{};return normalizeGate(S.gates[mid][g]||(S.gates[mid][g]=gateDefaults(g)),g)}
function previousGate(g){return g==='B'?'A':g==='C'?'B':null}
function reassessmentReady(mid,g){if(g==='A')return moduleDone(mid);const p=gs(mid,previousGate(g));return !!(p.attempt&&p.developing&&p.reviewViewed&&p.repairDone&&p.repairEvidence.trim())}
function moduleGatePassed(mid){return ['A','B','C'].some(g=>{const x=gs(mid,g);return x.assigned&&x.passed})}
function activeGate(mid){for(const g of ['C','B','A']){const x=gs(mid,g);if(x.assigned&&!x.passed)return g}return 'A'}
function resetLaterGates(mid,g){const later=g==='A'?['B','C']:g==='B'?['C']:[];for(const k of later)S.gates[mid][k]=gateDefaults(k)}
function status(x){const s=ls(x.lesson_id); if(s.mastered)return ['MASTERED','ok']; if(s.developing)return ['DEVELOPING','dev']; if(s.review)return ['RETRY + EXPLAIN','dev']; if(s.attempt)return ['REVIEW UNLOCKED','dev']; return ['NOT STARTED','']}
function pct(){return Math.round(CORE.filter(x=>ls(x.lesson_id).mastered).length/CORE.length*100)}
function moduleCore(mid){return CORE.filter(x=>x.module_id===mid)}
function moduleDone(mid){const a=moduleCore(mid);return a.length&&a.every(x=>ls(x.lesson_id).mastered)}
function nextAction(){
 for(const m of DATA.modules){
  const arr=moduleCore(m.module_id); const l=arr.find(x=>!ls(x.lesson_id).mastered);
  if(l){const s=ls(l.lesson_id); if(!s.attempt)return {kind:'learn',lesson:l,label:`Study ${l.lesson_id}: ${l.title}`,why:`Open the exact teaching page, do the mapped practice, then save a genuine attempt.`};
   if(!s.review)return {kind:'review',lesson:l,label:`Open ${l.lesson_id} protected review`,why:'Your genuine attempt is saved, so the review is now allowed.'};
   if(!s.retry)return {kind:'retry',lesson:l,label:`Complete ${l.lesson_id} changed retry`,why:'Close the review and solve the changed transfer before mastery.'};
   if(!s.explain)return {kind:'explain',lesson:l,label:`Teach back ${l.lesson_id}`,why:'Explain the idea in your own words before the Mastered button unlocks.'};
   return {kind:'master',lesson:l,label:`Mark ${l.lesson_id} mastered`,why:'Attempt, review, changed retry and explain-back are all recorded.'};
  }
  if(!moduleGatePassed(m.module_id)){const ag=activeGate(m.module_id),g=gs(m.module_id,ag);if(ag!=='A'&&!g.assigned){return {kind:'gateAssign',module:m,gate:ag,label:`Explicitly assign ${m.module_id} Gate ${ag}`,why:'A fresh full reassessment stays sealed until the failed Gate review and targeted repair evidence are recorded.'}}if(!g.attempt)return {kind:'gate',module:m,gate:ag,label:`Attempt ${m.module_id} Gate ${ag}`,why:ag==='A'?'All module lessons are mastered. Gate A is now the next competency check.':'The fresh reassessment was explicitly assigned after repair; take it independently.'};if(!g.reviewViewed)return {kind:'gateReview',module:m,gate:ag,label:`Review ${m.module_id} Gate ${ag}`,why:'Open the protected Gate review only after the saved assessment attempt.'};if(g.developing&&!g.repairDone)return {kind:'gateRepair',module:m,gate:ag,label:`Repair ${m.module_id} Gate ${ag} weakness`,why:'Record targeted repair plus a changed micro-proof before any later Gate can be assigned.'};if(g.developing){const ng=ag==='A'?'B':ag==='B'?'C':null;if(ng&&!gs(m.module_id,ng).assigned)return {kind:'gateAssign',module:m,gate:ng,label:`Explicitly assign ${m.module_id} Gate ${ng}`,why:'Repair is recorded; the fresh full reassessment still requires an explicit assignment.'};return {kind:'gateDecision',module:m,gate:ag,label:`Resolve ${m.module_id} Gate ${ag}`,why:'Do not advance while the Gate remains Developing.'}}return {kind:'gateDecision',module:m,gate:ag,label:`Record ${m.module_id} Gate ${ag} result`,why:'Pass the Gate or mark Developing and route to targeted repair.'};}
 }
 return {kind:'complete',label:'Core learning route complete',why:'All 114 core lessons and module Gate A records are complete. Course-level evidence/release review remains separate.'};
}
function nav(){const n=qs('#nav');n.innerHTML=TABS.map(t=>`<button data-tab="${t}" class="${S.activeTab===t?'active':''}">${t}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.activeTab=b.dataset.tab;save();render()})}
function openLink(h){if(!h)return;window.open(h,'_blank','noopener')}
function lessonActions(x){const s=ls(x.lesson_id);const [st,cl]=status(x);return `<div class="lesson" data-id="${x.lesson_id}"><div class="head"><div><b>${esc(x.lesson_id)} · ${esc(x.title)}</b><div class="muted">${esc(x.module_id)} · pages ${x.start_page}-${x.end_page} · practice ${esc(x.practice_id||'mapped task')}</div></div><span class="pill ${cl}">${st}</span></div><div class="btnrow"><a class="btn blue" href="${esc(x.teach_href)}" target="_blank" rel="noopener">Open teach p${x.start_page}</a>${x.practice_href?`<a class="btn" href="${esc(x.practice_href)}" target="_blank" rel="noopener">Open practice</a>`:''}<button class="btn" data-act="attempt" ${s.attempt?'disabled':''}>${s.attempt?'Attempt saved':'Save genuine attempt'}</button>${x.review_href?`<button class="btn warn" data-act="review" ${!s.attempt||s.review?'disabled':''}>${s.review?'Review opened':'Open protected review'}</button>`:`<button class="btn warn" data-act="review" ${!s.attempt||s.review?'disabled':''}>${s.review?'Review checkpoint recorded':'Record review checkpoint'}</button>`}<button class="btn" data-act="retry" ${!s.review||s.retry?'disabled':''}>${s.retry?'Changed retry done':'Changed retry complete'}</button><button class="btn" data-act="explain" ${!s.retry||s.explain?'disabled':''}>${s.explain?'Explain-back done':'Explain-back complete'}</button><button class="btn primary" data-act="master" ${!s.explain||s.mastered?'disabled':''}>${s.mastered?'Mastered':'Mark mastered'}</button><button class="btn danger" data-act="develop">Needs repair</button></div><div class="lockhelp">Mastered unlock path: genuine attempt → protected review/checkpoint → changed retry → explain-back. The button is disabled until the missing step is recorded.</div></div>`}
function bindLessonActions(root){root.querySelectorAll('.lesson').forEach(el=>{const id=el.dataset.id;const x=DATA.course.lessons.find(q=>q.lesson_id===id);el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const s=ls(id),a=b.dataset.act;if(a==='attempt')s.attempt=true;if(a==='review'){if(!s.attempt)return;if(x.review_href)openLink(x.review_href);s.review=true}if(a==='retry'){if(!s.review)return;s.retry=true}if(a==='explain'){if(!s.retry)return;s.explain=true}if(a==='master'){if(!s.explain)return;s.mastered=true;s.developing=false}if(a==='develop'){s.developing=true;s.mastered=false}save();render()})})}
function gateCard(mid,g='A',protectedGate=false){const item=DATA.gates[mid][g]||{assessment:[],data:[],review:[]};const st=gs(mid,g);if(g==='A'&&!moduleDone(mid))return `<div class="callout warn"><b>Gate A locked.</b> Master all lessons in this module first.</div>`;if(g!=='A'&&!st.assigned){const ready=reassessmentReady(mid,g);return `<div class="callout warn reassess" data-mid="${mid}" data-g="${g}"><b>Gate ${g} sealed.</b> ${ready?'The failed prior Gate, protected review, targeted repair and changed micro-proof are recorded. Explicit assignment is still required.':'It remains unreachable until the prior Gate has a saved failed attempt, opened protected review, recorded targeted repair and changed micro-proof.'}${ready?`<div class="btnrow"><button class="btn primary" data-assign-g="${g}" data-assign-mid="${mid}">Explicitly assign fresh Gate ${g}</button></div>`:''}</div>`}const status=st.passed?'PASSED':st.developing?'DEVELOPING':st.attempt?'ATTEMPT SAVED':'READY';return `<div class="lesson gate" data-mid="${mid}" data-g="${g}"><div class="head"><div><b>${mid} Gate ${g}${protectedGate?' · PROTECTED RETEST':''}</b><div class="muted">${status}</div></div></div><div class="filelist">${item.data.map(h=>`<a href="${esc(h)}" target="_blank">Data: ${esc(h.split('/').pop())}</a>`).join('')}${item.assessment.map(h=>`<a href="${esc(h)}" target="_blank">Assessment: ${esc(h.split('/').pop())}</a>`).join('')}</div><div class="btnrow"><button class="btn" data-gact="attempt" ${st.attempt?'disabled':''}>${st.attempt?'Gate attempt saved':'Save Gate attempt'}</button><button class="btn warn" data-gact="review" ${!st.attempt||st.reviewViewed?'disabled':''}>${st.reviewViewed?'Gate review opened':'Open protected Gate review'}</button><button class="btn primary" data-gact="pass" ${!st.reviewViewed||st.passed?'disabled':''}>${st.passed?'Gate passed':'Mark PASS'}</button><button class="btn danger" data-gact="dev" ${!st.reviewViewed?'disabled':''}>Mark Developing</button><button class="btn" data-gact="repair" ${!st.developing||!st.reviewViewed||st.repairDone?'disabled':''}>${st.repairDone?'Repair evidence recorded':'Record targeted repair + changed proof'}</button></div>${st.repairDone?`<div class="lockhelp">Repair evidence: ${esc(st.repairEvidence)}</div>`:''}<div class="lockhelp">Gate review opens only after a saved attempt. Gate B/C assessment files do not enter the DOM until an explicit reassessment assignment is recorded.</div></div>`}
function bindGates(root){root.querySelectorAll('[data-assign-g]').forEach(b=>b.onclick=()=>{const mid=b.dataset.assignMid,g=b.dataset.assignG;if(!reassessmentReady(mid,g))return;const st=gs(mid,g);st.assigned=true;save();render()});root.querySelectorAll('.gate').forEach(el=>el.querySelectorAll('[data-gact]').forEach(b=>b.onclick=()=>{const mid=el.dataset.mid,g=el.dataset.g,st=gs(mid,g),a=b.dataset.gact;if(a==='attempt')st.attempt=true;if(a==='review'){if(!st.attempt)return;(DATA.gates[mid][g].review||[]).forEach(openLink);st.review=true;st.reviewViewed=true}if(a==='pass'){if(!st.reviewViewed)return;st.passed=true;st.developing=false;st.repair=false;st.repairDone=false;st.repairEvidence=''}if(a==='dev'){if(!st.reviewViewed)return;st.developing=true;st.passed=false;st.repair=false;st.repairDone=false;st.repairEvidence='';resetLaterGates(mid,g)}if(a==='repair'){if(!(st.developing&&st.reviewViewed))return;const ev=prompt(`Record targeted repair evidence for ${mid} Gate ${g}. State what you repaired and the changed micro-proof you completed:`,'');if(!ev||!ev.trim())return;st.repair=true;st.repairDone=true;st.repairEvidence=ev.trim()}save();render()}))}
function today(){const n=nextAction();const done=CORE.filter(x=>ls(x.lesson_id).mastered).length;let action='';if(n.lesson){const x=n.lesson,s=ls(x.lesson_id);action=`<div class="kicker">One next action</div><h2>${esc(n.label)}</h2><p>${esc(n.why)}</p>${lessonActions(x)}`}else if(n.module){action=`<div class="kicker">One next action</div><h2>${esc(n.label)}</h2><p>${esc(n.why)}</p>${gateCard(n.module.module_id,n.gate)}`}else action=`<div class="kicker">One next action</div><h2>${esc(n.label)}</h2><p>${esc(n.why)}</p>`;return `<div class="grid"><section class="card">${action}</section><section class="card half"><div class="kicker">Core progress</div><div class="metric">${done} / 114</div><div class="progress"><i style="width:${pct()}%"></i></div><div class="muted">${pct()}% · PL-300 is separate and ${S.plEnabled?'enabled':'not enabled'}.</div></section><section class="card half"><div class="kicker">Study tracker</div>${sessionHtml()}</section><section class="card"><div class="callout"><b>Course position:</b> Course 2A is optional. Direct DA → DE remains Course 1 → C2B Bridge → C3. PL-300 and promotion readiness never unlock C3 by themselves.</div></section></div>`}
function sessionHtml(){if(S.activeSession)return `<div class="session"><button class="btn danger" id="sessionBtn">END STUDY</button><div class="state">Started ${new Date(S.activeSession.start).toLocaleString()}. No countdown timer is used.</div></div>`;return `<div class="session"><button class="btn primary" id="sessionBtn">START STUDY</button><div class="state">Manual start/end record. Duration is calculated only when you end the session.</div></div>`}
function bindSession(){const b=qs('#sessionBtn');if(!b)return;b.onclick=()=>{if(S.activeSession){const end=new Date(),st=new Date(S.activeSession.start);S.sessions.unshift({start:S.activeSession.start,end:end.toISOString(),minutes:Math.max(0,Math.round((end-st)/60000))});S.activeSession=null}else S.activeSession={start:new Date().toISOString()};save();render()}}
function learn(){const modsOpts=['ALL',...DATA.modules.map(m=>m.module_id)];const arr=(S.plEnabled?DATA.course.lessons:CORE).filter(x=>S.moduleFilter==='ALL'||x.module_id===S.moduleFilter);return `<div class="grid"><section class="card"><div class="head"><div><div class="kicker">Learn</div><h2>Exact lesson route</h2></div></div><div class="tabsmall">${modsOpts.map(m=>`<button data-filter="${m}" class="${S.moduleFilter===m?'active':''}">${m}</button>`).join('')}</div><div class="callout" style="margin-top:12px">Every lesson opens the exact frozen teaching page and mapped practice file. Reviews remain locked until a genuine attempt is saved.</div>${arr.map(lessonActions).join('')}</section></div>`}
function course(){return `<div class="grid"><section class="card"><div class="kicker">Course</div><h2>10-module optional Senior / BI path</h2><p class="muted">Module Gates are competency checks. Gate B/C are protected fresh retests - not extra homework - and stay sealed until explicitly assigned after repair evidence.</p></section>${DATA.modules.map(m=>{const arr=moduleCore(m.module_id),d=arr.filter(x=>ls(x.lesson_id).mastered).length;const gp=moduleGatePassed(m.module_id);return `<section class="card half module"><div class="head"><div><b>${m.module_id} · ${esc(m.module_title)}</b><div class="muted">${d}/${arr.length} lessons · Gate A ${gp?'PASS':'pending'}</div></div><span class="pill ${gp?'ok':''}">${Math.round(d/arr.length*100)}%</span></div><div class="progress"><i style="width:${d/arr.length*100}%"></i></div><div class="btnrow"><a class="btn" href="${esc(m.start_href)}" target="_blank">Open Start Here</a></div><details><summary>Gate route</summary>${gateCard(m.module_id,'A')}${gateCard(m.module_id,'B',true)}${gateCard(m.module_id,'C',true)}</details></section>`}).join('')}<section class="card"><div class="callout warn"><b>PL-300:</b> ${S.plEnabled?'Enabled in Learn as an optional lane.':'Disabled by default.'} It does not count toward the 114 core lesson denominator.</div></section></div>`}
function repair(){const weak=CORE.filter(x=>ls(x.lesson_id).developing||(!ls(x.lesson_id).mastered&&ls(x.lesson_id).review));const gweak=[];for(const m of DATA.modules)for(const g of ['A','B','C'])if(gs(m.module_id,g).developing)gweak.push([m,g]);return `<div class="grid"><section class="card"><div class="kicker">Repair</div><h2>Target only weak competencies</h2><p class="muted">Do not restart strong modules. Preserve the failed attempt, repair the weak concept, then use a changed retest.</p>${weak.length?weak.map(x=>`<div class="lesson"><b>${x.lesson_id} · ${esc(x.title)}</b><div class="field"><label>Repair note</label><textarea data-repair="${x.lesson_id}" placeholder="What failed? What will you change? What evidence will prove the repair?">${esc(S.repairNotes[x.lesson_id]||'')}</textarea></div><div class="btnrow"><a class="btn blue" href="${esc(x.teach_href)}" target="_blank">Re-open exact teaching</a></div></div>`).join(''):'<div class="empty">No lesson is currently marked Developing.</div>'}</section><section class="card">${gweak.length?gweak.map(([m,g])=>gateCard(m.module_id,g)).join(''):'<div class="empty">No Gate is currently marked Developing.</div>'}</section></div>`}
function evidence(){const arr=CORE.filter(x=>ls(x.lesson_id).attempt||ls(x.lesson_id).mastered);return `<div class="grid"><section class="card"><div class="kicker">Evidence</div><h2>Evidence notes</h2><p class="muted">Store only short references/notes here; keep real files in the course project folders. Do not paste secrets or confidential workplace data.</p>${arr.length?arr.map(x=>`<div class="lesson"><b>${x.lesson_id} · ${esc(x.title)}</b><div class="field"><textarea data-evidence="${x.lesson_id}" placeholder="Evidence ID, artifact path, validation result, limitation...">${esc(S.evidence[x.lesson_id]||'')}</textarea></div></div>`).join(''):'<div class="empty">Evidence fields appear after you save a lesson attempt.</div>'}</section></div>`}
function jobs(){return `<div class="grid"><section class="card"><div class="kicker">Jobs</div><h2>Senior / BI promotion and job-switch evidence</h2><div class="callout danger"><b>Truth boundary:</b> Course/synthetic project evidence is not employer production experience, salary impact, or years of work.</div><div class="btnrow"><a class="btn blue" target="_blank" href="../COURSE_MODULES/C2_09/04_CAREER/C2_09_PROMOTION_AND_JOB_SWITCH_READINESS_WORKBOOK_RC1.xlsx">Open readiness workbook</a><a class="btn" target="_blank" href="../COURSE_MODULES/C2_09/04_CAREER/C2_09_SENIOR_BI_INTERVIEW_COMPANION_RC1.pdf">Interview companion</a><a class="btn" target="_blank" href="../COURSE_MODULES/C2_09/04_CAREER/C2_09_COURSE_2A_COMPLETION_RECORD_RC1.pdf">Completion record</a></div><div class="field"><label>Career notes</label><textarea id="careerNotes" placeholder="Target role, evidence gaps, truthful next action...">${esc(S.careerNotes||'')}</textarea></div></section><section class="card half"><h3>Optional PL-300</h3><p class="muted">Separate certification lane. Current official objectives must be rechecked before exam payment.</p><a class="btn" target="_blank" href="../COURSE_MODULES/C2_09/05_PL300_OPTIONAL/C2_09_PL300_SUPPLEMENT_TEACHING_BOOK_RC1.pdf">Open PL-300 supplement</a></section><section class="card half"><h3>Optional DE transition evidence</h3><p class="muted">Transfer evidence only; direct route still uses C2B/C3.</p><a class="btn" target="_blank" href="../COURSE_MODULES/C2_09/06_DE_TRANSITION_OPTIONAL/C2_09_C2A_TO_DE_READINESS_CHECK_RC1.pdf">Open DE readiness check</a></section></div>`}
function reports(){const mastered=CORE.filter(x=>ls(x.lesson_id).mastered).length,attempts=CORE.filter(x=>ls(x.lesson_id).attempt).length,dev=CORE.filter(x=>ls(x.lesson_id).developing).length,gpass=DATA.modules.filter(m=>moduleGatePassed(m.module_id)).length;return `<div class="grid"><section class="card third"><div class="kicker">Core mastered</div><div class="metric">${mastered}/114</div></section><section class="card third"><div class="kicker">Attempts</div><div class="metric">${attempts}</div></section><section class="card third"><div class="kicker">Gate A pass</div><div class="metric">${gpass}/10</div></section><section class="card half"><h3>Study sessions</h3>${S.sessions.length?S.sessions.slice(0,15).map(x=>`<div class="route"><b>•</b><div>${new Date(x.start).toLocaleString()} · ${x.minutes} min</div></div>`).join(''):'<div class="muted">No completed sessions yet.</div>'}</section><section class="card half"><h3>Backup / restore</h3><p class="muted">Backup includes progress, evidence notes, settings and study sessions. It does not include your actual project files.</p><div class="btnrow"><button class="btn blue" id="backupBtn">Download backup JSON</button><label class="btn">Restore backup<input id="restoreInput" type="file" accept="application/json" hidden></label><button class="btn danger" id="resetBtn">Reset Mentor progress</button></div></section><section class="card"><div class="callout"><b>Developing lessons:</b> ${dev}. A low number is not a target; unresolved weak evidence is better marked Developing than hidden.</div></section></div>`}
function settings(){return `<div class="grid"><section class="card half"><div class="kicker">Settings</div><h2>Appearance</h2><div class="field"><label>Theme</label><select id="themeSel"><option value="light">Light</option><option value="dark">Dark</option><option value="amoled">AMOLED black</option><option value="system">System</option></select></div><div class="field"><label>Text size</label><select id="fontSel"><option value="0.9">Compact</option><option value="1">Standard</option><option value="1.1">Large</option><option value="1.2">Extra large</option></select></div></section><section class="card half"><h2>Optional lane</h2><div class="field"><label><input id="plToggle" type="checkbox" ${S.plEnabled?'checked':''}> Show PL1-PL8 inside Learn</label></div><p class="muted">This never changes the 114-core progress denominator or C2A completion.</p></section><section class="card"><h3>Interaction model</h3>${['Today = one next action','Learn = exact page + mapped practice','Course = modules and Gates','Repair = only weak competencies','Evidence = saved proof notes','Jobs = truthful promotion/job-switch readiness','Reports = progress + backup/restore','Settings = theme + optional lanes'].map((x,i)=>`<div class="route"><b>${i+1}</b><div>${x}</div></div>`).join('')}</section></div>`}
function render(){applyTheme();nav();let h='';switch(S.activeTab){case'Today':h=today();break;case'Learn':h=learn();break;case'Course':h=course();break;case'Repair':h=repair();break;case'Evidence':h=evidence();break;case'Jobs':h=jobs();break;case'Reports':h=reports();break;case'Settings':h=settings();break}const m=qs('#main');m.innerHTML=h;bindLessonActions(m);bindGates(m);bindSession();m.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{S.moduleFilter=b.dataset.filter;save();render()});m.querySelectorAll('[data-repair]').forEach(t=>t.onchange=()=>{S.repairNotes[t.dataset.repair]=t.value;save()});m.querySelectorAll('[data-evidence]').forEach(t=>t.onchange=()=>{S.evidence[t.dataset.evidence]=t.value;save()});const cn=qs('#careerNotes');if(cn)cn.onchange=()=>{S.careerNotes=cn.value;save()};const th=qs('#themeSel');if(th){th.value=S.theme;th.onchange=()=>{S.theme=th.value;save();render()}}const fs=qs('#fontSel');if(fs){fs.value=String(S.fontScale);fs.onchange=()=>{S.fontScale=Number(fs.value);save();render()}}const pl=qs('#plToggle');if(pl)pl.onchange=()=>{S.plEnabled=pl.checked;save();render()};bindReports();}
function toast(t){const el=qs('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function bindReports(){const b=qs('#backupBtn');if(b)b.onclick=()=>{const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='COURSE_2A_MENTOR_BACKUP.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Backup created')};const r=qs('#restoreInput');if(r)r.onchange=()=>{const f=r.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const obj=JSON.parse(rd.result);if(!obj||typeof obj!=='object')throw Error();S=Object.assign(fresh(),obj);save();render();toast('Backup restored')}catch(e){toast('Invalid backup file')}};rd.readAsText(f)};const z=qs('#resetBtn');if(z)z.onclick=()=>{if(confirm('Reset Mentor progress on this browser? Your course files are not deleted.')){S=fresh();save();render()}}}
window.addEventListener('hashchange',()=>{});if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
})();
