const mk=(id,name,ids,titles,hours,artifacts)=>({id,name,hours,artifacts,lessons:ids.map((x,i)=>({id:x,title:titles[i]||x}))});
const seq=(p,n)=>Array.from({length:n},(_,i)=>`${p}${i+1}`);
window.COURSE2=[
mk('C2-00','Senior Analyst Foundations',seq('SAF',8),['Junior vs senior responsibility','Vague stakeholder requests -> scoped analysis','Requirements gathering & clarification meetings','KPI ownership & metric contracts','Grain, lineage & source-of-truth','Assumptions, risks, limitations & judgment','Validation & reconciliation','Inheritable documentation'],[18,24],{lesson:'C2-011',practice:'C2-012',review:'C2-013',lab:'C2-014',gate:'C2-015A'}),
mk('C2-01','Advanced Excel & Power Query',seq('AX',10),['Advanced formulas without spaghetti','XLOOKUP, INDEX/MATCH','Dynamic arrays: FILTER/UNIQUE/SORT','SUMIFS & COUNTIFS','Advanced PivotTables','Power Query architecture & repeatable imports','Multiple-file cleaning & transforms','Merge vs append & grain mistakes','Parameters & reusable query design','Refreshable monthly reporting'],[25,32],{lesson:'C2-021',practice:'C2-022',review:'C2-023',lab:'C2-024',gate:'C2-025A'}),
mk('C2-02','Advanced SQL',seq('ASQL',12),['Joins & grain','Subqueries & derived tables','CTEs & readable architecture','Window functions','Ranking, partitions & running calculations','LAG/LEAD & time analysis','Conditional aggregation & KPIs','Date/time analysis','Data-quality investigation','Debugging & validation','Performance concepts: indexes/scans/execution awareness','Maintainable production analytical SQL'],[32,42],{lesson:'C2-031',practice:'C2-033',review:'C2-034',lab:'C2-035/036',gate:'C2-037A'}),
mk('C2-03','Professional Power BI Modeling',seq('PBM-A',10),['Semantic-model thinking','Fact & dimension tables','Star schema','Relationships & filter propagation','Cardinality & many-to-many risks','Role-playing dimensions','Date dimensions','Power Query architecture for BI','Validation & reconciliation','Performance fundamentals'],[25,32],{lesson:'C2-041',practice:'C2-042',review:'C2-044',lab:'C2-045',gate:'C2-046A'}),
mk('C2-04','Advanced DAX, Reporting & PL-300',seq('DAX',15),['Evaluation context','Row context & filter context','CALCULATE','Iterators','Context transition','Time intelligence','Period comparisons & rolling metrics','Variables & readable DAX','Advanced business measures','Debugging incorrect measures','Report storytelling & executive design','Drill-through, tooltips, bookmarks & interactions','Accessibility & usability','Row-level security','Workspaces, sharing & lifecycle basics'],[32,42],{lesson:'C2-051',practice:'C2-052',review:'C2-054',lab:'C2-055',gate:'C2-056A'}),
mk('C2-05','Python Automation for Analysts',seq('PYA',11),['Reusable scripts','Functions & modularity','Robust pandas','Multi-file processing','Excel automation','CSV & JSON','APIs','Error handling & defensive scripts','Logging & validation','Recurring reporting automation','Reproducible analytical pipelines'],[25,34],{lesson:'C2-061',practice:'C2-062',review:'C2-064',lab:'C2-065',gate:'C2-066A'}),
mk('C2-06','Data Warehousing & Platform Foundations',seq('DWF',12),['Operational DB vs analytical systems','OLTP vs OLAP','Data warehouses','Facts, dimensions & dimensional modeling','Surrogate vs business keys','Slowly changing dimensions','ETL vs ELT','Staging -> transform -> presentation','Lakes & lakehouses','Batch vs streaming','Lineage & metadata','Data quality controls'],[24,32],{lesson:'C2-071',practice:'C2-072',review:'C2-073',lab:'C2-074',gate:'C2-075A'}),
mk('C2-07','Cloud, Fabric & Enterprise BI',seq('CLD',10),['Cloud data fundamentals','Compute, storage & identity','Microsoft Fabric ecosystem','OneLake, lakehouse & warehouse','Power BI Service in enterprise','Workspaces & deployment','Refresh, gateways & scheduled operations','Permissions & governance','Monitoring & failure awareness','Analyst <-> analytics engineer <-> data engineer collaboration'],[20,28],{lesson:'C2-081',practice:'C2-082',review:'C2-083',lab:'C2-084',gate:'C2-085A'}),
mk('C2-08','Senior Business Analysis & Communication',seq('SBA',12),['Stakeholder discovery','Challenge a bad request professionally','Prioritization','Observation vs inference vs recommendation','Executive summaries','Uncertainty','Recommendations tied to decisions','Contradictory requirements','Defend analysis','Cross-functional work','Code review, documentation & handoff','Mentor & review junior work'],[20,28],{lesson:'C2-091',practice:'C2-092',review:'C2-093',lab:'C2-094',gate:'C2-095A'}),
mk('C2-09','Senior Analyst Capstone, PL-300 & Promotion',[...seq('CAP',14),...seq('PL',8)],['Ambiguous requirements','Acquisition/source choice','SQL extraction','Transform via the right tool','Modeling','Analysis','Power BI report','Validation','Executive communication','Documentation','Technical defense','Senior Analyst interview','Internal promotion case','External job-switch prep','Current exam objectives audit','Prepare Data assessment','Model Data assessment','Visualize & Analyze assessment','Manage & Secure assessment','Microsoft-style practice assessment','Weak-area repair','Certification readiness gate'],[35,50],{lesson:'C2-101/108',practice:'C2-102/109',review:'C2-105/110',lab:'Capstone',gate:'C2-111A'})
];
