(()=>{
  const TIMER_KEY='daMentorAdvance.timer.v2';
  const getTools=()=>{
    if(!state.studyTools)state.studyTools={};
    const t=state.studyTools,d={focusMin:25,shortMin:5,longMin:15,alarm:'on',dailyTarget:3,focusLog:[],streak:{lastDate:'',count:0},tasks:[],notes:{}};
    for(const [k,v] of Object.entries(d))if(t[k]===undefined)t[k]=Array.isArray(v)?[]:typeof v==='object'?JSON.parse(JSON.stringify(v)):v;
    if(!Array.isArray(t.focusLog))t.focusLog=[];if(!t.streak)t.streak={lastDate:'',count:0};return t;
  };
  const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const modeDuration=m=>{const t=getTools();return m==='focus'?Math.max(10,+t.focusMin||25):m==='short'?Math.max(1,+t.shortMin||5):Math.max(5,+t.longMin||15)};
  const makeIdle=(m='focus')=>({v:2,status:'idle',mode:m,durationMin:modeDuration(m),remainingSec:modeDuration(m)*60,startedAt:0,endAt:0,phase:'',sessionId:'',completedAt:0});
  const loadTimer=()=>{try{const x=JSON.parse(localStorage.getItem(TIMER_KEY)||'null');return x&&x.v===2?Object.assign(makeIdle(x.mode||'focus'),x):makeIdle()}catch(e){return makeIdle()}};
  let T=loadTimer();
  const store=()=>localStorage.setItem(TIMER_KEY,JSON.stringify(T));
  const persist=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const rem=()=>T.status==='running'?Math.max(0,Math.ceil((T.endAt-Date.now())/1000)):Math.max(0,+T.remainingSec||0);
  const fmtClock=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
  const fmtM=m=>{m=Math.round(+m||0);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`};
  const minsToday=()=>getTools().focusLog.filter(x=>x.date===todayKey()).reduce((a,x)=>a+(+x.minutes||0),0);
  const logged=id=>getTools().focusLog.some(x=>x&&x.sessionId===id);
  function updateStreak(){const t=getTools(),day=todayKey();if(t.streak.lastDate===day)return;const y=new Date();y.setDate(y.getDate()-1);const yk=`${y.getFullYear()}-${String(y.getMonth()+1).padStart(2,'0')}-${String(y.getDate()).padStart(2,'0')}`;t.streak.count=t.streak.lastDate===yk?(t.streak.count||0)+1:1;t.streak.lastDate=day}
  const askNotification=()=>{try{if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}catch(e){}};
  const signal=async(title,body)=>{const t=getTools();if(t.alarm!=='on')return;try{if(navigator.vibrate)navigator.vibrate([180,80,180,80,260])}catch(e){}try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=780;g.gain.value=.06;o.start();setTimeout(()=>{o.stop();ctx.close()},500)}catch(e){}try{if('Notification'in window&&Notification.permission==='granted'){if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag:'mentor-focus-complete',renotify:true})}else new Notification(title,{body})}}catch(e){}};
  function draw(){const clock=document.getElementById('proTimerClock'),start=document.getElementById('proTimerStart'),hint=document.getElementById('proTimerHint'),today=document.getElementById('proFocusToday');if(!clock||!start)return;clock.textContent=T.status==='complete'?'00:00':fmtClock(rem());start.textContent=T.status==='running'?'PAUSE':T.status==='complete'?'DONE':'START';document.querySelectorAll('[data-pro-timer-mode]').forEach(b=>b.classList.toggle('active',b.dataset.proTimerMode===T.mode));if(today)today.textContent=`${fmtM(minsToday())} focus today`;const tools=getTools();if(hint)hint.textContent=T.status==='complete'?`✅ ${T.mode==='focus'?`${T.durationMin}m focus saved to Reports`:'Break complete'} — tap DONE`:T.mode==='focus'?`Target ${tools.dailyTarget}h • ${tools.streak.count||0} day streak 🔥${T.status==='running'?' • background-safe tracking':''}`:'Breaks do not add to study time.';const tt=document.getElementById('proTargetText'),tb=document.getElementById('proTargetBar'),ts=document.getElementById('proTargetSummary');if(tt||tb||ts){const m=minsToday(),target=(+tools.dailyTarget||3)*60,pc=Math.min(100,Math.round(m/Math.max(1,target)*100));if(tt)tt.textContent=`${fmtM(m)} / ${tools.dailyTarget}h`;if(tb)tb.style.width=pc+'%';if(ts)ts.textContent=`${pc}% of today's target. Mastery still matters more than timer time.`}}
  function reset(m=T.mode){T=makeIdle(m);store();draw()}
  async function complete(){if(T.status==='complete')return;const tools=getTools(),id=T.sessionId||`advance-${T.startedAt||Date.now()}`,minutes=+T.durationMin||modeDuration(T.mode),phase=T.phase||state.currentPhase||'C2-00',focus=T.mode==='focus';T.status='complete';T.remainingSec=0;T.endAt=0;T.completedAt=Date.now();T.sessionId=id;store();if(focus&&!logged(id)){tools.focusLog.push({date:todayKey(),minutes,phase,sessionId:id,startedAt:T.startedAt||0,completedAt:T.completedAt});updateStreak();persist()}draw();await signal(focus?'Focus session complete':'Break complete',focus?`${minutes} minutes saved to DA Mentor Advance reports.`:'Your break is finished.')}
  function reconcile(){if(T.status==='running'&&rem()<=0)complete();else draw()}
  function toggle(){if(T.status==='complete'){reset(T.mode);return}if(T.status==='running'){T.remainingSec=rem();T.status='paused';T.endAt=0;store();draw();return}const wasPaused=T.status==='paused',seconds=wasPaused&&T.remainingSec>0?T.remainingSec:modeDuration(T.mode)*60;T.status='running';T.durationMin=wasPaused?(+T.durationMin||modeDuration(T.mode)):modeDuration(T.mode);T.remainingSec=seconds;T.startedAt=T.startedAt||Date.now();T.endAt=Date.now()+seconds*1000;T.phase=T.phase||state.currentPhase||'C2-00';T.sessionId=T.sessionId||`advance-${T.startedAt}-${Math.random().toString(36).slice(2,8)}`;store();askNotification();draw()}
  function setMode(m){if(!['focus','short','long'].includes(m))return;reset(m)}
  function stripOldTimerListeners(){const shell=document.querySelector('.focusTimerCard .timerShell');if(!shell)return;const clone=shell.cloneNode(true);shell.replaceWith(clone)}
  function install(){stripOldTimerListeners();document.querySelectorAll('[data-pro-timer-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.proTimerMode));document.getElementById('proTimerStart')?.addEventListener('click',toggle);document.getElementById('proTimerReset')?.addEventListener('click',()=>reset(T.mode));document.getElementById('saveSettingsBtn')?.addEventListener('click',()=>setTimeout(()=>{if(T.status==='idle')reset(T.mode);else draw()},0));['pageshow','focus','online'].forEach(ev=>window.addEventListener(ev,reconcile));document.addEventListener('visibilitychange',reconcile);setInterval(reconcile,1000);reconcile()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
