(()=>{
  const KEY2='daMentorAdvance.studySession.v1';
  const tools=()=>{if(!state.studyTools)state.studyTools={focusLog:[],streak:{lastDate:'',count:0}};if(!Array.isArray(state.studyTools.focusLog))state.studyTools.focusLog=[];if(!state.studyTools.streak)state.studyTools.streak={lastDate:'',count:0};return state.studyTools};
  const dayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const load=()=>{try{return Object.assign({active:false,startedAt:0,phase:'',sessionId:''},JSON.parse(localStorage.getItem(KEY2)||'{}'))}catch(e){return {active:false,startedAt:0,phase:'',sessionId:''}}};let S=load();
  const persistSession=()=>localStorage.setItem(KEY2,JSON.stringify(S));const hostPersist=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const fmtElapsed=ms=>{const total=Math.floor(Math.max(0,ms)/1000),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
  const fmtMinutes=m=>m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`;const elapsed=()=>S.active?Date.now()-S.startedAt:0;const startLabel=()=>S.startedAt?new Date(S.startedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';
  function updateStreak2(){const t=tools(),today=dayKey();if(t.streak.lastDate===today)return;const y=new Date();y.setDate(y.getDate()-1);const yk=`${y.getFullYear()}-${String(y.getMonth()+1).padStart(2,'0')}-${String(y.getDate()).padStart(2,'0')}`;t.streak.count=t.streak.lastDate===yk?(t.streak.count||0)+1:1;t.streak.lastDate=today}
  function installUI(){const card=document.querySelector('.focusTimerCard');if(!card)return;const h=card.querySelector('h2');if(h)h.textContent='Manual study session';const shell=card.querySelector('.timerShell');if(!shell)return;shell.innerHTML=`<div class="muted tiny">Use your phone Clock for Pomodoro alarms. Mentor records only between START STUDY and END STUDY.</div><div class="focusClock" id="studySessionClock">00:00</div><div class="row timerControls"><button class="btn primary" id="studySessionToggle">START STUDY</button><button class="btn" id="studySessionCancel">Cancel</button></div><div class="muted tiny" id="studySessionHint" style="margin-top:9px"></div>`;document.getElementById('studySessionToggle').onclick=toggle;document.getElementById('studySessionCancel').onclick=cancel;draw()}
  function draw(){const c=document.getElementById('studySessionClock'),b=document.getElementById('studySessionToggle'),x=document.getElementById('studySessionCancel'),h=document.getElementById('studySessionHint');if(!c||!b)return;c.textContent=fmtElapsed(elapsed());b.textContent=S.active?'END STUDY':'START STUDY';if(x)x.disabled=!S.active;if(h)h.textContent=S.active?`Started ${startLabel()} • reopening Mentor does not end it.`:'Session ends only when you press END STUDY.'}
  function start(){S={active:true,startedAt:Date.now(),phase:state.currentPhase||'C2-00',sessionId:`advance-study-${Date.now()}-${Math.random().toString(36).slice(2,8)}`};persistSession();draw()}
  function end(){if(!S.active)return;const ended=Date.now(),minutes=Math.max(1,Math.round((ended-S.startedAt)/60000)),id=S.sessionId,t=tools();if(!t.focusLog.some(x=>x&&x.sessionId===id))t.focusLog.push({date:dayKey(),minutes,phase:S.phase||state.currentPhase||'C2-00',sessionId:id,startedAt:S.startedAt,completedAt:ended,source:'manual-study-session'});updateStreak2();S={active:false,startedAt:0,phase:'',sessionId:''};persistSession();hostPersist();render();draw();alert(`Study session saved: ${fmtMinutes(minutes)}.`)}
  function toggle(){S.active?end():start()}function cancel(){if(!S.active)return;if(!confirm('Cancel this active study session without saving it?'))return;S={active:false,startedAt:0,phase:'',sessionId:''};persistSession();draw()}function reconcile(){S=load();draw()}
  function init(){installUI();window.addEventListener('focus',reconcile);window.addEventListener('pageshow',reconcile);document.addEventListener('visibilitychange',reconcile);setInterval(draw,1000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
