(()=>{
 const names={midnight:'Midnight',slate:'Slate',forest:'Forest',ocean:'Ocean',ember:'Ember',graphite:'Graphite'};
 const desc={midnight:'Signature violet',slate:'Cool professional',forest:'Deep green',ocean:'Blue cyan',ember:'Warm executive',graphite:'Minimal monochrome'};
 const swatches={midnight:'linear-gradient(135deg,#0b1020,#8b7cf6)',slate:'linear-gradient(135deg,#11151b,#69a7ff)',forest:'linear-gradient(135deg,#0c1512,#53d18f)',ocean:'linear-gradient(135deg,#071622,#2ab7ca)',ember:'linear-gradient(135deg,#1b100d,#f28c5d)',graphite:'linear-gradient(135deg,#111214,#8a94a3)'};
 const settings=document.getElementById('themeInput');
 ['ocean','ember','graphite'].forEach(v=>{if(settings&&![...settings.options].some(o=>o.value===v)){const o=document.createElement('option');o.value=v;o.textContent=names[v];settings.appendChild(o)}});
 const trigger=document.getElementById('proThemeMenuBtn'),pop=document.getElementById('proThemePopover'),legacy=document.getElementById('themeCycleBtn');trigger?.remove();pop?.remove();legacy?.remove();
 const style=document.createElement('style');style.textContent=`.proSettingsThemes{margin:12px 0}.proSettingsThemes>span{display:block;margin-bottom:8px}.proSettingsThemeGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.proSettingsThemeCard{display:flex;gap:9px;align-items:center;text-align:left;border:1px solid var(--bd);background:var(--panel2);color:var(--txt);border-radius:13px;padding:10px;cursor:pointer}.proSettingsThemeCard.active{outline:2px solid var(--accent);border-color:var(--accent)}.proSettingsThemeCard i{width:38px;height:38px;border-radius:11px;flex:0 0 38px}.proSettingsThemeCard b,.proSettingsThemeCard small{display:block}.proSettingsThemeCard small{color:var(--mut);margin-top:2px}@media(max-width:520px){.proSettingsThemeGrid{grid-template-columns:1fr}}`;document.head.appendChild(style);
 const modal=document.querySelector('#settingsModal .modalCard');let gallery=document.getElementById('proSettingsThemes');if(modal&&!gallery){const themeLabel=settings?.closest('label');if(themeLabel)themeLabel.style.display='none';gallery=document.createElement('div');gallery.id='proSettingsThemes';gallery.className='proSettingsThemes';gallery.innerHTML=`<span class="muted tiny">Appearance</span><div class="proSettingsThemeGrid">${Object.keys(names).map(k=>`<button type="button" class="proSettingsThemeCard" data-pro-settings-theme="${k}"><i style="background:${swatches[k]}"></i><span><b>${names[k]}</b><small>${desc[k]}</small></span></button>`).join('')}</div>`;const saveRow=document.getElementById('saveSettingsBtn')?.parentElement;modal.insertBefore(gallery,saveRow||null)}
 function current(){return (typeof state!=='undefined'&&state.theme)||document.body.dataset.theme||'midnight'}
 function sync(){const t=current();if(settings)settings.value=t;document.querySelectorAll('[data-pro-settings-theme]').forEach(b=>b.classList.toggle('active',b.dataset.proSettingsTheme===t))}
 gallery?.addEventListener('click',e=>{const b=e.target.closest('[data-pro-settings-theme]');if(!b||typeof state==='undefined')return;state.theme=b.dataset.proSettingsTheme;if(settings)settings.value=state.theme;if(typeof save==='function')save();sync()});
 document.getElementById('settingsBtn')?.addEventListener('click',()=>setTimeout(sync,0));document.getElementById('saveSettingsBtn')?.addEventListener('click',()=>setTimeout(sync,0));sync();
})();